# version: "3.9"

services:
  linklian-core:
    build: .
    expose:
      - "5400"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5400/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - linklian-net
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/etc/nginx:ro
    depends_on:
      - linklian-core
    networks:
      - linklian-net

networks:
  linklian-net:
    external: true