# version: "3.9"

services:
  linklian-core:
    build: .
    # ports:
    #   - "5400:5400"
    expose:
      - "5400"
    # volumes:
    #   - .:/app
      # - /app/node_modules
    env_file:
      - .env
    command: npm run start:prod
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5400/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # deploy:
    #   mode: replicated
    #   replicas: 3      # รัน 3 Instances พร้อมกัน
    #   restart_policy:
    #     condition: on-failure
    mem_limit: 500m
    restart: on-failure
    networks:
      - linklian-net
    
  nginx:
    image: nginx:latest
    container_name: linklian-load-balancer
    ports:
      - "80:80"
    mem_limit: 200m
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - linklian-core
    networks:
      - linklian-net

networks:
  linklian-net:
    external: true